import {schema,examples,buildSQL} from './data.mjs';
const $=id=>document.getElementById(id),KEY='database-playground-v1';
let worker,seq=0,pending=null,bytes=null,tables={},undo=[],mode='guided',table='customers',view='customers',action='search',ready=false,lastChanges=[],selected=null;
const esc=x=>String(x??'NULL').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const say=(text,error=false)=>{$('notice').textContent=text;$('notice').classList.toggle('error',error);};
function lock(b){document.body.classList.toggle('busy',b);for(const el of document.querySelectorAll('button, select, input, textarea'))el.disabled=b||!ready;$('undo').disabled=b||!ready||!undo.length;$('retry').disabled=b;$('reset').disabled=b;}
function call(type,payload={}){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending=null;worker.terminate();reject(Error(type==='init'?'準備に時間がかかっています。もう一度読み込んでください。':'実行が8秒を超えたため中断しました。データは実行前に戻します。'));},type==='init'?20000:8000);pending={id,resolve,reject,timer};worker.postMessage({id,type,...payload});});}
function spawn(){worker?.terminate();worker=new Worker(new URL('./worker.js?v=1',import.meta.url));worker.onmessage=({data})=>{if(!pending||pending.id!==data.id)return;const p=pending;pending=null;clearTimeout(p.timer);data.error?p.reject(Error(data.error)):p.resolve(data);};worker.onerror=()=>{if(pending){clearTimeout(pending.timer);pending.reject(Error('データベースを読み込めませんでした。通信を確認して再試行してください。'));pending=null;}};}
function save(){try{let s='';for(const n of bytes)s+=String.fromCharCode(n);localStorage.setItem(KEY,btoa(s));$('saveState').textContent='このブラウザに保存済み · 他の人とは共有されません';}catch{$('saveState').textContent='保存できないため、このページを閉じると変更が失われます';}}
function read(){try{const raw=localStorage.getItem(KEY);return raw?Uint8Array.from(atob(raw),c=>c.charCodeAt(0)):null;}catch{return null;}}
async function boot(initial=bytes){ready=false;lock(true);$('retry').hidden=true;spawn();try{const r=await call('init',{bytes:initial});bytes=r.bytes;tables=r.tables;ready=true;renderAll();save();say('準備できました。「検索を実行」を押して、京都のお客さんを取り出してみよう。');}catch(e){say(e.message,true);$('retry').hidden=false;}finally{lock(false);}}
function currentRows(t=table){return tables[t]?.values||[];}
function rowObject(t,row){return Object.fromEntries(Object.keys(schema[t].columns).map((k,i)=>[k,row?.[i]??'']));}
function renderTable(id,data,base=false){const el=$(id);if(!data){el.innerHTML='';return;}el.innerHTML='<thead><tr>'+data.columns.map(c=>`<th>${esc(base?schema[view].columns[c]:c)}${base?`<small>${esc(c)}</small>`:''}</th>`).join('')+'</tr></thead><tbody>'+(data.values.length?data.values.map(row=>{const change=base&&lastChanges.find(x=>x.table===view&&x.id===row[0]);return `<tr class="${change?.type||''}">`+row.map((v,i)=>`<td class="${change?.before&&change.before[i]!==v?'changed':''}">${base&&i===0?`<button data-row="${esc(v)}" aria-label="ID ${esc(v)}の行を更新">${esc(v)}</button>`:esc(v)}</td>`).join('')+'</tr>';}).join(''):`<tr><td class="empty" colspan="${Math.max(1,data.columns.length)}">該当するデータはありません</td></tr>` )+'</tbody>';}
function renderData(){for(const t of Object.keys(schema)){$('n-'+t).textContent=currentRows(t).length;document.querySelector(`[data-table="${t}"]`).setAttribute('aria-pressed',String(t===view));}$('tableHint').textContent=schema[view].description;renderTable('dataTable',tables[view],true);}
const tips={search:'条件に合う行を取り出します。元の表のデータは変わりません。',add:'新しい行を1件追加します。IDは自動で割り当てます。',update:'選んだIDの行だけを書き換えます。変更前と変更後を比べてみよう。',delete:'選んだ行を削除します。注文に使われている顧客・商品は削除できません。'};
function fields(){const meta=schema[table],rows=currentRows();$('actionHint').textContent=tips[action];$('runGuided').textContent=({search:'検索',add:'追加',update:'更新',delete:'削除'})[action]+'を実行 →';document.querySelectorAll('[data-action]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.action===action)));
 let html='';
 if(action==='search'){html=`<label class="field">どの列を？<select name="column">${Object.entries(meta.columns).map(([k,v])=>`<option value="${k}" ${k===(table==='customers'?'city':table==='products'?'category':'customer_id')?'selected':''}>${v} · ${k}</option>`).join('')}</select></label><label class="field">どんな値？（完全一致・空欄なら全件）<input name="value" value="${table==='customers'?'京都':''}" placeholder="例：京都"></label>`;}
 else{
  let obj={};if(action!=='add'){if(!rows.some(r=>r[0]===selected))selected=rows[0]?.[0]??null;obj=rowObject(table,rows.find(r=>r[0]===selected));html=`<label class="field">変更する行<select name="id">${rows.length?rows.map(r=>`<option value="${r[0]}" ${r[0]===selected?'selected':''}>ID ${r[0]} · ${esc(r[1])}</option>`).join(''):'<option value="">行がありません</option>'}</select></label>`;}
  else obj=table==='customers'?{name:'新しいお客さん',city:'京都',member:'一般'}:table==='products'?{name:'新しい雑貨',category:'文具',price:1000,stock:10}:{customer_id:currentRows('customers')[0]?.[0]||1,product_id:currentRows('products')[0]?.[0]||1,quantity:1,unit_price:currentRows('products')[0]?.[3]||0,ordered_at:'2026-09-08'};
  if(action!=='delete')for(const [key,type] of Object.entries(meta.types)){
   const ref=key==='customer_id'?'customers':key==='product_id'?'products':null;
   const control=ref?`<select name="${key}">${currentRows(ref).map(r=>`<option value="${r[0]}" ${r[0]===Number(obj[key])?'selected':''}>${r[0]} · ${esc(r[1])}</option>`).join('')}</select>`:`<input name="${key}" type="${type}" value="${esc(obj[key])}" ${type==='number'?`min="${key==='quantity'?1:0}" step="1"`:''} required>`;
   html+=`<label class="field">${meta.columns[key]}<span class="micro">${key}</span>${control}</label>`;
  }
 }
 $('fields').innerHTML=html;preview();}
function formValues(){return Object.fromEntries(new FormData($('form')));}
function preview(){try{$('generated').textContent=buildSQL(table,action,formValues());}catch(e){$('generated').textContent=e.message;}}
function relation(){const rows=currentRows('orders'),keep=Number($('orderSelect').value);$('orderSelect').innerHTML=rows.map(r=>`<option value="${r[0]}">注文 #${r[0]} · ${esc(r[5])}</option>`).join('');if(rows.some(r=>r[0]===keep))$('orderSelect').value=keep;drawRelation();}
function drawRelation(){const row=currentRows('orders').find(r=>r[0]===Number($('orderSelect').value));if(!row){$('relationCards').innerHTML='<p class="hint">注文がありません。操作で試す → 注文 → 追加で作れます。</p>';return;}const c=currentRows('customers').find(r=>r[0]===row[1]),p=currentRows('products').find(r=>r[0]===row[2]);$('relationCards').innerHTML=`<div class="relation origin"><small>orders / id = ${row[0]}</small><strong>注文 #${row[0]}</strong><span>${row[3]}個 · ${esc(row[5])}</span></div><div class="connection">customer_id = ${row[1]} → customers.id</div><div class="relation"><small>顧客 ID ${row[1]}</small><strong>${esc(c?.[1])}</strong><span>${esc(c?.[2])}</span></div><div class="connection">product_id = ${row[2]} → products.id</div><div class="relation"><small>商品 ID ${row[2]}</small><strong>${esc(p?.[1])}</strong><span>購入時単価 ${Number(row[4]).toLocaleString()}円</span></div>`;}
function renderAll(){renderData();fields();relation();}
function switchMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('guided').hidden=mode!=='guided';$('sqlPanel').hidden=mode!=='sql';$('relations').hidden=mode!=='relations';$('controlTitle').textContent=mode==='guided'?'何をしてみる？':mode==='sql'?'SQLで指示してみる':'IDでつながる表';}
function explainError(s){if(/FOREIGN KEY/i.test(s))return '参照先のIDが存在しないか、この行が注文から使われています。顧客・商品・注文のつながりを確認してください。';if(/UNIQUE/i.test(s))return 'そのIDはすでに使われています。主キーは重複できません。';if(/CHECK/i.test(s))return '値のルールに合いません。名前は空欄にせず、価格・在庫は0以上、個数は1以上にしてください。';if(/NOT NULL/i.test(s))return '必須の値が空です。すべての必須項目を入力してください。';return s;}
async function execute(sql){if(!ready)return;lock(true);const before=bytes;try{const r=await call('run',{sql});tables=r.tables;bytes=r.bytes;lastChanges=r.changes;if(r.changes.length){undo.push(before);if(undo.length>10)undo.shift();view=r.changes[0].table;}renderData();relation();save();$('outcome').hidden=false;const count=r.result[0]?.values.length??0;$('resultTitle').textContent=r.changes.length?'データが変わりました':r.result.length?'検索結果':'変更はありません';$('resultMeta').textContent=r.changes.length?`${r.changes.length}行に変更`:`${count}行`;$('diff').innerHTML=r.changes.map(c=>{const cols=Object.keys(schema[c.table].columns),detail=c.type==='updated'?cols.map((k,i)=>c.before[i]!==c.after[i]?`${schema[c.table].columns[k]}: ${esc(c.before[i])} → ${esc(c.after[i])}`:'').filter(Boolean).join(' / '):(c.after||c.before).map(esc).join(' · ');return `<div class="change"><strong>${schema[c.table].name} #${c.id} · ${({added:'追加',updated:'更新',deleted:'削除'})[c.type]}</strong>${detail}</div>`;}).join('');renderTable('resultTable',r.result[0]);$('resultNote').textContent=r.changes.length?'元の表にも変更が反映されました。「ひとつ戻す」で取り消せます。':r.result.length?'元の表は変わっていません。上の実行結果だけを取り出しました。':'データの変更はありません。指定したID・条件や、変更前の値を確認してください。';say(r.changes.length?`${r.changes.length}行の変更を反映しました。`:`実行しました。結果は${count}行です。`);if(action==='delete')fields();$('outcome').scrollIntoView({behavior:'auto',block:'nearest'});}catch(e){$('outcome').hidden=true;say('実行できませんでした。'+explainError(e.message),true);if(e.message.includes('8秒')){await boot(before);say(e.message,true);}}finally{lock(false);}}
$('form').addEventListener('submit',e=>{e.preventDefault();try{execute(buildSQL(table,action,formValues()));}catch(err){say(err.message,true);}});
$('fields').addEventListener('input',preview);$('fields').addEventListener('change',e=>{if(e.target.name==='id'){selected=Number(e.target.value);fields();}else{if(table==='orders'&&action==='add'&&e.target.name==='product_id'){const p=currentRows('products').find(r=>r[0]===Number(e.target.value));$('form').elements.unit_price.value=p?.[3]||0;}preview();}});
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{action=b.dataset.action;fields();});
$('tableSelect').onchange=()=>{table=$('tableSelect').value;view=table;selected=null;fields();renderData();};
document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{view=b.dataset.table;renderData();});
$('dataTable').onclick=e=>{const b=e.target.closest('[data-row]');if(!b)return;table=view;$('tableSelect').value=table;selected=Number(b.dataset.row);action='update';switchMode('guided');fields();$('form').scrollIntoView({behavior:'auto',block:'nearest'});};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$('example').innerHTML=examples.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');
function chooseExample(){const x=examples[Number($('example').value)];$('sql').value=x.sql;$('exampleHint').textContent=x.hint;}
$('example').onchange=chooseExample;chooseExample();$('runSQL').onclick=()=>execute($('sql').value);
$('orderSelect').onchange=drawRelation;$('join').onclick=()=>{switchMode('sql');$('example').value='2';chooseExample();execute($('sql').value);};
$('undo').onclick=async()=>{if(!undo.length)return;const previous=undo[undo.length-1];await boot(previous);if(ready){undo.pop();lastChanges=[];$('outcome').hidden=true;renderAll();lock(false);say('直前の変更を取り消しました。');}};
$('reset').onclick=async()=>{const previous=bytes;await boot(null);if(ready){undo.push(previous);if(undo.length>10)undo.shift();lastChanges=[];renderAll();$('outcome').hidden=true;lock(false);say('サンプルの初期状態に戻しました。この操作も「ひとつ戻す」で取り消せます。');}};
$('retry').onclick=()=>boot(bytes);bytes=read();boot(bytes);
